services:
  # API Gateway
  - type: web
    name: biblioteca-gateway
    runtime: docker
    plan: free
    repo: https://github.com/ViniciuSetorio/biblioteca-api
    branch: main
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    envVars:
      - fromGroup: biblioteca-secrets
      - key: NODE_ENV
        value: production
      - key: USUARIOS_URL
        value: http://biblioteca-usuarios:3001
      - key: LIVROS_URL
        value: http://biblioteca-livros:3002
      - key: EMPRESTIMOS_URL
        value: http://biblioteca-emprestimos:3003
      - key: MULTAS_URL
        value: http://biblioteca-multas:3004
      - key: FRONTEND_URL
        value: https://bibton.vercel.app/


  # Serviço de Usuários
  - type: web
    name: biblioteca-usuarios
    runtime: docker 
    plan: free
    repo: https://github.com/ViniciuSetorio/biblioteca-api
    branch: main
    dockerfilePath: ./servico-usuarios/Dockerfile
    dockerContext: ./servico-usuarios
    envVars:
      - fromGroup: biblioteca-secrets
      - key: NODE_ENV
        value: production
      - key: EMPRESTIMOS_SERVICE_URL
        value: http://biblioteca-emprestimos:3003
      - key: PORT
        value: 3001

  # Serviço de Livros
  - type: web
    name: biblioteca-livros
    runtime: docker 
    plan: free
    repo: https://github.com/ViniciuSetorio/biblioteca-api
    branch: main
    dockerfilePath: ./servico-livros/Dockerfile
    dockerContext: ./servico-livros
    envVars:
      - fromGroup: biblioteca-secrets
      - key: NODE_ENV
        value: production
      - key: USUARIOS_SERVICE_URL
        value: http://biblioteca-usuarios:3001
      - key: EMPRESTIMOS_SERVICE_URL
        value: http://biblioteca-emprestimos:3003
      - key: PORT
        value: 3002

  # Serviço de Empréstimos
  - type: web
    name: biblioteca-emprestimos
    runtime: docker 
    plan: free
    repo: https://github.com/ViniciuSetorio/biblioteca-api
    branch: main
    dockerfilePath: ./servico-emprestimos/Dockerfile
    dockerContext: ./servico-emprestimos
    envVars:
      - fromGroup: biblioteca-secrets
      - key: NODE_ENV
        value: production
      - key: USUARIOS_SERVICE_URL
        value: http://biblioteca-usuarios:3001
      - key: LIVROS_SERVICE_URL
        value: http://biblioteca-livros:3002
      - key: MULTAS_SERVICE_URL
        value: http://biblioteca-multas:3004
      - key: NOTIFICACOES_SERVICE_URL
        value: http://biblioteca-notificacoes:3005
      - key: PORT
        value: 3003

  # Serviço de Multas
  - type: web
    name: biblioteca-multas
    runtime: docker 
    plan: free
    repo: https://github.com/ViniciuSetorio/biblioteca-api
    branch: main
    dockerfilePath: ./servico-multas/Dockerfile
    dockerContext: ./servico-multas
    envVars:
      - fromGroup: biblioteca-secrets
      - key: NODE_ENV
        value: production
      - key: EMPRESTIMOS_SERVICE_URL
        value: http://biblioteca-emprestimos:3003
      - key: PORT
        value: 3004

  # Serviço de Notificações
  - type: web
    name: biblioteca-notificacoes
    runtime: docker 
    plan: free
    repo: https://github.com/ViniciuSetorio/biblioteca-api
    branch: main
    dockerfilePath: ./servico-notificacoes/Dockerfile
    dockerContext: ./servico-notificacoes
    envVars:
      - fromGroup: biblioteca-secrets
      - key: NODE_ENV
        value: production
      - key: USUARIOS_SERVICE_URL
        value: http://biblioteca-usuarios:3001
      - key: EMPRESTIMOS_SERVICE_URL
        value: http://biblioteca-emprestimos:3003
      - key: LIVROS_SERVICE_URL
        value: http://biblioteca-livros:3002
      - key: PORT
        value: 3005