CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  cargo VARCHAR(50) CHECK (cargo IN ('bibliotecario', 'membro')) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);